version: '3.8'

services: 
  db:
    container_name: cooking-recipes-postgres
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=${TYPEORM_USERNAME}
      - POSTGRES_PASSWORD=${TYPEORM_PASSWORD}
      - POSTGRES_DB=${TYPEORM_DATABASE}
    volumes: 
      - ./pgdata:/var/lib/postgresql/data/
    ports:
      - ${TYPEORM_PORT}:${TYPEORM_PORT}
  backend:
    container_name: cooking-recipes-backand
    build: 
      context: ./
    depends_on:
      - db
    restart: unless-stopped
    environment:
      - APP_PORT=${APP_PORT}
      - TYPEORM_CONNECTION=${TYPEORM_CONNECTION}
      - TYPEORM_USERNAME=${TYPEORM_USERNAME}
      - TYPEORM_PASSWORD=${TYPEORM_PASSWORD}
      - TYPEORM_DATABASE=${TYPEORM_DATABASE}
      - TYPEORM_PORT=${TYPEORM_PORT}
      - TYPEORM_HOST=db
    ports:
      - ${APP_PORT}:${APP_PORT}